#!/bin/bash
if ! [ -d ~/.bdb/ ] ; then
	git clone https://github.com/bytebutcher/bdb ~/.bdb/
fi

if ! [ -f ~/.bdb/bdb.sh ] ; then
	echo "ERROR: Installation of bdb failed!" >&2
	exit 1
fi

cat <<EOF > ~/.bdb.bash
unalias bdb 2> /dev/null
bdb() {
unalias bdb 2> /dev/null
bdb() {
   bookmark_location="\$(bdb.sh \$@)"
   if [ \$? -eq 0 ] && [ -n "\${bookmark_location}" ] ; then
      cd "\${bookmark_location}"
   fi
}
export -f bdb > /dev/null
export PATH=~/.bdb/:\${PATH}
EOF

if ! [ -f ~/.bdb.bash ] ; then
	echo "ERROR: Installation of bdb failed!" >&2
	exit 1
fi

result="$(grep "[ -f ~/.bdb.bash ] && source ~/.bdb.bash" ~/.bashrc)"
if [ -z "${result}" ]  ; then
	echo "[ -f ~/.bdb.bash ] && source ~/.bdb.bash" >> ~/.bashrc
fi

echo "Finished. Restart your shell or reload config file."
[[ "$shells" =~ bash ]] && echo "   source ~/.bashrc  # bash"
#[[ "$shells" =~ zsh ]]  && echo "   source ${ZDOTDIR:-~}/.zshrc   # zsh"
#[[ "$shells" =~ fish ]] && [ $key_bindings -eq 1 ] && echo "   fzf_key_bindings  # fish"
